### ISSUE TITLE
C AST Architecture Discussion

### ISSUE THREAD

**Issue by HMPerson1** [radareorg/radeco-lib#136]

**Comment by kriw** [comment]
C AST is defined [here](https://github.com/radare/radeco-lib/blob/master/src/backend/lang_c/c_simple.rs). 
For converting IR -> AST, I think we need more simple C-AST which have only necessary operator such as `Div`, `Mul` instead of `Shr`, `Shl` and only `Goto`s instead of `Loop`, `Break`.
What I mean is to define another struct as a subset of [CASTNode](https://github.com/radare/radeco-lib/blob/master/src/backend/lang_c/c_simple.rs#L97).
So the decompilation process would be
1. IR -> Simple C-AST 
2. Simple C-AST -> C-AST (remove Gotos, elaborate exprs)

This is slightly indirect approach, but I think each process would be clearer.

**Comment by chinmaydd** [comment]
The idea seems good to me 👍 

We should expose a mechanism to allow the user to implement analysis passes over both the AST structures in this case and improve overall decompilation. Can help evaluate PoC algorithms.

**Comment by kriw** [comment]
This is my detailed idea,

## Simple C-AST
This is equivalent to block by block C-AST.
The block is a slice of instructions which starts from function's entrypoint or end point of jmp, branch instruction, also ends at the end of function, or jmp, branch instruction.

```rust
enum SimpleCASTNode {
    Constant(Ty, String),
    Var(String),
    ExpressionNode(Expr),
    Conditional,
    Goto(u64),
}
```

CASTEdge and Expr node of the AST can be same to the C-AST which is final output.
Possibly we can implement Simple C-AST just by replacing CASTNode in [CAST](https://github.com/radare/radeco-lib/blob/master/src/backend/lang_c/c_simple.rs#L147) with SimpleCASTNode or creating generic types.

## IR -> Simple C-AST

We need to slice instructions into expressions.

## Simple C-AST -> C-AST

1. I will implement simple Simple C-AST to C-AST convert which have `Goto`s at first. (GSoC week 1 ~ 4)
2. @HMPerson1 will implement the algorithm of structuring control flow. (GSoC week 5 ~ 8)

**Comment by kriw** [comment]
I have submitted PR #145.
The architecture of SimpleCAST in the PR is different from the one mentioned above.
The architecture is similar to `SSAStorage`. Each node is value or action. Value represents variable or immediate value, action represents call, goto, assignment, etc.
